# Generated by Django 5.0.7 on 2024-08-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date_birth', models.DateField()),
                ('origin_country', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
