# Generated by Django 5.0.7 on 2024-08-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
