version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data2
    environment:
      POSTGRES_DB: Review_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200"]
      interval: 30s
      timeout: 1s
      retries: 5


  web:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py seed_data && python manage.py seed_data && python manage.py collectstatic --noinput && gunicorn goodreads.wsgi:application --bind 0.0.0.0:80 --access-logfile -"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
      - "80:80"
    depends_on:
      db:
        condition: service_healthy


      
    environment:
      - DATABASE_NAME=Review_app_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DJANGO_SERVE_STATIC=False
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200


volumes:
  postgres_data:
  esdata01: