# Generated by Django 5.0.7 on 2024-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date_birth', models.DateField()),
                ('origin_country', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('date_of_pub', models.DateTimeField()),
                ('num_sales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('score', models.IntegerField()),
                ('num_upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=200)),
                ('sales', models.IntegerField(default=0)),
            ],
        ),
    ]
